name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:


jobs:
  Download:
     runs-on: ubuntu-latest
     steps:
     
      - uses: actions/download-artifact@v3
        with:
          name: upload
      - name: Display structure of downloaded files
        run: ls -R
     
     
#       - name: Release
#         uses: softprops/action-gh-release@v1
#         with:
#           files: target/${{ matrix.target }}/release/hello_world.${{ matrix.extension }}
#           append_body: true
